### ISSUE TITLE
endpoint to query current status

### ISSUE THREAD

**Issue by pieper** [ImagingDataCommons/ThrottleProxy#3]
OHIF is adding the ability to handle http errors like those generated when an IP hits the threshold by this proxy (https://github.com/OHIF/Viewers/issues/1598).

But we want to be able to give users some advance warning, like a notification that they are close to the limit or maybe an area that turns yellow then red as you get close to the limit.

Can we have an api endpoint to query the current usage compared to the cap?

**Comment by wlongabaugh** [comment]
OK, just saw this issue. Sounds like a good idea. Should be able to do this.

**Comment by wlongabaugh** [comment]
Feature checked in.
